# fly.toml app configuration file generated for llm-student-project on 2024-05-26T12:42:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'llm-student-project'
primary_region = 'atl'

[build]
  dockerfile = "Dockerfile"
  compose = "docker-compose.yml"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
